// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using controleCobranca.Data;

namespace controleCobranca.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("controleCobranca.Models.Cliente", b =>
                {
                    b.Property<int>("indice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("bairro")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<int>("cdContrato")
                        .HasColumnType("int");

                    b.Property<string>("cep")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<string>("cidade")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("complemento")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.Property<DateTime>("dataEnvio")
                        .HasColumnType("DateTime");

                    b.Property<string>("destinatario")
                        .IsRequired()
                        .HasColumnType("varchar(80)");

                    b.Property<string>("endereco")
                        .IsRequired()
                        .HasColumnType("varchar(120)");

                    b.Property<int>("lote")
                        .HasColumnType("int");

                    b.Property<int>("nrTermo")
                        .HasColumnType("int");

                    b.Property<string>("numero")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("obs")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("registroPlano")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.Property<string>("uf")
                        .IsRequired()
                        .HasColumnType("char(2)");

                    b.Property<decimal>("valor")
                        .HasColumnType("money");

                    b.Property<DateTime>("vencimento")
                        .HasColumnType("DateTime");

                    b.HasKey("indice");

                    b.ToTable("controleCobranca", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
